name: Verify layouts
on:
  push:
    branches: ['main']
  pull_request:
jobs:
  verify-layouts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Verify test standard layout
        run: |
          go run main.go -l layouts/layout.yml -a test-data
      - name: Verify test NPM layout
        run: |
          go run main.go -l layouts/layout-npm.yml -a test-data-npm --substitute-parameters parameters/npm-sigstore.json
