name: Verify layouts
on:
  push:
    branches: ['main']
  pull_request:
jobs:
  verify-layouts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          check-latest: true
          go-version-file: 'go.mod'
      - name: Verify test standard layout
        run: |
          go run main.go -l layouts/layout.yml -a test-data
      - name: Verify test NPM layout
        run: |
          go run main.go -l layouts/layout-npm.yml -a test-data-npm --substitute-parameters parameters/npm-sigstore.json
