name: gittuf Verification
on:
  push:
    branches: ['main']
jobs:
  gittuf-verify:
    if: github.repository == 'in-toto/attestation-verifier'
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@da8c392f92d2f7f2e50db8457951395bfb593e15
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          cd attestation-verifier
          gittuf verify-ref main --verbose
