name: gittuf Verification
on:
  push:
    branches: ['main']
jobs:
  gittuf-verify:
    if: github.repository == 'in-toto/attestation-verifier'
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@a9730b348241599ca1882a8844acb43cd7935bb7
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          cd attestation-verifier
          gittuf verify-ref main --verbose
