name: gittuf Verification
on:
  push:
    branches: ['main']
jobs:
  gittuf-verify:
    if: github.repository == 'in-toto/attestation-verifier'
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@b31d2ba4f494f30fbc44371da67ad87cca6569f9
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          cd attestation-verifier
          gittuf verify-ref main --verbose
