name: gittuf Verification
on:
  push:
    branches: ['main']
jobs:
  gittuf-verify:
    if: github.repository == 'in-toto/attestation-verifier'
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@172d0010e16eb0f54537f37fca567a8d4b0a56e5
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          cd attestation-verifier
          gittuf verify-ref main --verbose
